default: &DEFAULT
  log: true
  log_level: INFO
  randomize_hosts: true
  reload_connections: true
  reload_on_failure: true
  retry_on_failure: 1
  transport_options:
    ca_file: "/etc/logstash/certs/elasticsearch-ca.pem"
    ssl:
      verify: false

development:
  <<: *DEFAULT
  retry_on_failure: false

test:
  <<: *DEFAULT

production:
  <<: *DEFAULT
  log_level: WARN
